### ISSUE TITLE
AI Lua scripts not working on MXE builds

### ISSUE THREAD

**Issue by enjgine** [TheJosh/chaotic-rage#106]
Running V1.9 on Win 8.1, recieved 
![untitled](https://cloud.githubusercontent.com/assets/2782170/4089671/a401422e-2f70-11e4-8cd6-c21fa4ce9dec.png)

**Comment by TheJosh** [comment]
This should be fixed as of 58b8c63 and 4e7081d6; need to run the MXE binary on a Windows machine to confirm.

I've compiled a test one here -- http://dev1.chaoticrage.com/test/chaoticrage-mxe-2015-05-01.zip

I'm going to hopefully find time to test tonight.

**Comment by TheJosh** [comment]
Oop nevermind. MXE builds are still borken - that ZIP file doesn't actually contain the .exe!

**Comment by TheJosh** [comment]
Okay, I've got another MXE build, and it's actually got a .exe now!
http://dev1.chaoticrage.com/test/chaoticrage-mxe-2015-05-04.zip

**Comment by TheJosh** [comment]
Linux and Android automated builds using new Lua are available on the build server
http://dev1.chaoticrage.com/test/

**Comment by TheJosh** [comment]
I confirmed this morning that the MXE cross compiled build works correctly on Windows 7 and does not exhibit the Lua bug we were seeing previously.
