### ISSUE TITLE
Travis CI for Android is very unreliable

### ISSUE THREAD

**Issue by esper** [TheJosh/chaotic-rage#107]
Travis fails to build for Android around 50% of the cases. It makes the CI very unreliable and is very annoying. Report the error in the logs or create a workaround.

I use the Travis script to build Android and have never got this fault locally with my low-end computer running Ubuntu 14.04 64-bits.

Build logs (most of the failed builds are reported as a compiler bug):
https://travis-ci.org/TheJosh/chaotic-rage/builds

Example of "failed" Android build:
```
[armeabi-v7a] Compile++ thumb: assimp <= LWOLoader.cpp
arm-linux-androideabi-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
make: *** [obj/local/armeabi-v7a/objs/assimp/code/LWOLoader.o] Error 4
make: *** Waiting for unfinished jobs....
arm-linux-androideabi-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
make: *** [obj/local/armeabi-v7a/objs/assimp/code/IFCReaderGen.o] Error 4
The command "tools/travis/script.sh" exited with 1.
Done. Your build exited with 1.
```

**Comment by TheJosh** [comment]
I think it might be the OOM killer.
http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

**Comment by TheJosh** [comment]
I think this is mostly working now that I've made some changes to lower the memory requirements.

**Comment by esper** [comment]
Still not stable Android builds unfortunately https://travis-ci.org/TheJosh/chaotic-rage/jobs/61377790

**Comment by TheJosh** [comment]
I've told Travis to ignore Android build failures. I don't know what else we can do until the ram situation improves or the compilers are able to operate using less ram.
