### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by TheJosh** [TheJosh/chaotic-rage#120]
Hey @zapateo, you appear to be from Italy. Would you like to help us out with an Italian translation? If you're interested, I can provide instructions on how to make a translation.

**Comment by zapateo** [comment]
Yes of course ;)

**Comment by TheJosh** [comment]
Hi @zapateo. I've added a page with translation instructions to the website.
http://chaoticrage.com/dev_docs/tutorials/adding_a_language

**Comment by zapateo** [comment]
Thanks a lot, I'll do it as soon as possible.
