### ISSUE TITLE
Compiles without warnings, But failed to load cr mod

### ISSUE THREAD

**Issue by wlxmhls** [TheJosh/chaotic-rage#129]
Hello, I compiles the chaotic rage code 1.15 in Debian 10 buster x86_64 with no error. When I try to run ./chaoticrage , the main window pops up, reporting "FATAL ERROR: Unable to load mod 'cr'."  The console prints out:

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Bad definition in file unittypes.conf at index 0: Invalid node_head
FATAL ERROR: Unable to load mod 'cr'.

I checked the data/cr/unittypes.conf : 
unittype {
	name = "robot"
	health = 5000
	playable = 1
	
	model = "undefined_man.dae"
	node_head = "Neck"

	max_speed = 6.2
	melee_damage = 4000
	melee_delay = 500
	melee_cooldown = 500
	health_regen_delay = 5000
	health_regen_speed = 50.0
	
	sound { type = 3  sound = "man_death1.wav" }

	spawn_weapons = { "shotgun", "proxi_mine", "pistol" }
	special_weapon = "blackhole"
	
	animation { type = 1  animation = 0  start_frame = 1   end_frame = 6  loop = 1 }
	animation { type = 3  animation = 0  start_frame = 6  end_frame = 8  loop = 0 }
	
	death_debris = { "blood_splat.dae" }
}
... ...

Then the main window exits.

How to solve it?

Env:  Debian 10 x86_64,  gcc (Debian 8.3.0-6) 8.3.0 ,  SDL 2.0.9,  SDL-Mixer 2.0.4, SDL-image 2.0.4, sdl-net 2.0.1, libglu1-mesa 9.0.0, libglew 2.1.0,  freetype 2.9.1, bullet 2.87,  libassimp 4.1.0,  libmicrohttp 0.9.62

**Comment by TheJosh** [comment]
I've pushed a possible fix. Can you try again with the latest 'master' commit?
