### ISSUE TITLE
Get Chaotic Rage into Debian archive

### ISSUE THREAD

**Issue by esper** [TheJosh/chaotic-rage#98]
Creating this issue as an continuation of the discussions in the commit bad7a7c6f8a243d7fd2d9dffb941c92729279ee6.

The goal is to get Chaotic Rage in to the Debian archive, which would also add Chaotic Rage to all Debian forks such as Ubuntu. This is a great way to spread our project and make it easy for the users, could also attract more developers.

Josh has a contact that might be able to help us.

https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#adding-packages-to-debian
https://www.debian.org/doc/manuals/developers-reference/

**Comment by TheJosh** [comment]
I'm going to contact the Debian Games Team and see if we can get th is packaged and uploaded.

**Comment by TheJosh** [comment]
Request-For-Package has been added:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784590

**Comment by TheJosh** [comment]
Debian packages are now built using the buildtool server (which is running Debian 8 Jessie). This will become available as of next week in the weekly builds, and in the next release.

You can get the test build from here:
http://dev1.chaoticrage.com/test/chaoticrage_2015-05-07_amd64.deb

**Comment by TheJosh** [comment]
If we get in before August, we should also get into Ubuntu.

**Comment by TheJosh** [comment]
From chat in IRC:
the usual procedure is: decide you want to make a package, file an ITP (intent to package), do the packaging, upload to mentors.d.o, file an RFS (request for sponsor)

**Comment by TheJosh** [comment]
I've updated the packaging today. It's now two packages as per their guidelines, and I also don't package the dejavu font but depend on that package instead. This means we're now lintian clean.

**Comment by TheJosh** [comment]
http://mentors.debian.net/package/chaoticrage

**Comment by TheJosh** [comment]
I've added a RFS bug to Debian -- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788407
